site_name: Isabella's Portfolio
site_url: https://isabela-pf.github.io/portfolio/

theme:
    name: material

    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    palette:
        scheme: default
        primary: pink

    features:
        - navigation.tabs

plugins:
    - search

# https://squidfunk.github.io/mkdocs-material/setup/extensions/
markdown_extensions:
    - admonition

# https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
nav:
    - Projects: index.md
    - About: about.md
    - Contact: contact.md
    - Speaking: speaking.md
    - Reading: reading.md
    - Writing: writing.md
